<?php

/**
 * @file
 * Drupal hooks and functions to work with taxonomy terms.
 *
 * Redirect URL can be set for each separate taxonomy term.
 *
 *
 * (C) Neurones technologies
 * author : Michel Bobillier
 */

function myphp_views_api() {
    return array("api" => "3.0");
}





function _myphp_split_rows($vars, $columns, $horizontal = TRUE) {
    $col = 0;
    $row = 0;
    $items = array();
    $remainders = count($vars['rows']) % $columns;
    $num_rows = floor(count($vars['rows']) / $columns);

    // Iterate over each rendered views result row.
    foreach ($vars['rows'] as $item) {

        // Add the item.
        if ($horizontal) {
            $items[$row]['content'][$col]['content'] = $item;
        }
        else {
            $items[$col]['content'][$row]['content'] = $item;
        }

        // Increase, decrease or reset appropriate integers.
        if ($horizontal) {
            if ($col == 0 && $col != ($columns - 1)) {
                $col++;
            }
            elseif ($col >= ($columns - 1)) {
                $col = 0;
                $row++;
            }
            else {
                $col++;
            }
        }
        else {
            $row++;
            if (!$remainders && $row == $num_rows) {
                $row = 0;
                $col++;
            }
            elseif ($remainders && $row == $num_rows + 1) {
                $row = 0;
                $col++;
                $remainders--;
            }
        }
    }

    return $items;
}









/**
 * Implements hook_taxonomy_menu_path().
 */
function myphp_taxonomy_menu_path()
{
    $output = array(
        'myphp_path_default' => t('Rubric'),
    );

    return $output;
}



/**
 * Callback for hook_taxonomy_menu_path
 */
function myphp_path_default($vid, $tid) {
    // if tid = 0 then we are creating the vocab menu item format will be taxonomy/term/$tid+$tid+$tid....
    if ($tid == 0) {
        // get all of the terms for the vocab
        $vtids = _taxonomy_menu_get_terms($vid);
        $end = implode(' ', $vtids);
        $path = "taxonomy/term/".$end;
    }
    else {
        $parents=taxonomy_get_parents_all($tid);
        $i=0;
        while( $term = array_pop($parents )) {
            $data['f['.$i++.']'] = 'field_rubric:'.$term->tid;
        }


        $path = 'rubric?'.http_build_query($data);
    }
    return $path;
}
