<?php
/**
 * @file
 * Code for the feature_base feature.
 */

include_once 'feature_base.features.inc';

function feature_base_init(){

}

/**
 * Set the themes.
 *
 */
function feature_base_enable()
{

    module_disable(array('toolbar','search'));
    theme_enable(array('myphp', 'seven'));

    // Default theme
    variable_set('theme_default', 'myphp');

    // Admin theme
    variable_set('admin_theme', 'seven');
    variable_set('node_admin_theme', 1);

    theme_disable(array('bartik', 'responsive_bartik'));

    // Allow anonymous and authenticated users to search content
   // user_role_grant_permissions(DRUPAL_ANONYMOUS_RID, array('search content'));
   // user_role_grant_permissions(DRUPAL_AUTHENTICATED_RID, array('search content'));
  //  module_enable(array('search_api_db'));
//    $database_server = search_api_server_load('database_server');
//    $database_index = search_api_index_load('database_node_index');
 //   $database_server->fieldsUpdated($database_index);

}