<?php
/**
 * @file
 * Code for the feature_base feature.
 */

include_once 'feature_base.features.inc';

function feature_base_init(){

}

/**
 * Set the themes.
 *
 */
function feature_base_update_7000()
{
    theme_enable(array('tweme', 'seven'));

    // Default theme
    variable_set('theme_default', 'tweme');

    // Admin theme
    variable_set('admin_theme', 'sevent');
    variable_set('node_admin_theme', 1);

    theme_disable(array('bartik', 'responsive_bartik'));
}