<?php
/**
 * @file
 * Code for the feature_base feature.
 */

include_once 'feature_base.features.inc';

function feature_base_init(){

}

/**
 * Set the themes.
 *
 */
function feature_base_enable()
{

    module_disable(array('toolbar'));
    theme_enable(array('tweme', 'seven'));

    // Default theme
    variable_set('theme_default', 'tweme');

    // Admin theme
    variable_set('admin_theme', 'seven');
    variable_set('node_admin_theme', 1);

    theme_disable(array('bartik', 'responsive_bartik'));
}