<?php

/**
 * @file
 * Drupal hooks and functions to work with taxonomy terms.
 *
 * Redirect URL can be set for each separate taxonomy term.
 *
 *
 * (C) Neurones technologies
 * author : Michel Bobillier
 */

/**
 * Implements hook_init().
 */
function myphp_taxonomy_redirect_init()
{
    $x=arg();
    if (arg(1) == 'term' && is_numeric(arg(2)) && !arg(3) && strtolower(substr($_GET['q'],0,7)) == 'rubric/') {
        drupal_goto('rubric', array('query'=>array('f[]'=>'field_tag:'.arg(2))));
    }
}


